name: Build and run unit tests
on:
  pull_request:
  workflow_call:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🏭 Setup repo
        uses: actions/checkout@v3

      - name: 🏭 Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: 🏭 Install dependencies
        run: npm install

      # - name: 🕵️‍♀️ Run Unit Tests
      #   run: npm test
